In [2]:
import datetime
import json
import re
import requests

from alpaca.data.historical import StockHistoricalDataClient
from alpaca.data.requests import StockBarsRequest
from alpaca.data.timeframe import TimeFrame
from bs4 import BeautifulSoup
import pandas as pd
import pytz
import talib

## fetch Alpaca's pricing data

In [3]:
with open('./Alpaca API Key.txt') as file:
    API_KEY = file.readline()
with open('./Alpaca API Secret.txt') as file:
    API_SECRET = file.readline()
    
client = StockHistoricalDataClient(API_KEY, API_SECRET)

In [4]:
def fetch_pricing_data(client, symbol, start, end):
    request_params = StockBarsRequest(symbol_or_symbols=[f'{symbol}'], timeframe=TimeFrame.Minute, start=start, end=end) # note that Alpaca returns all data from IEX in UTC timestamps
    bars = client.get_stock_bars(request_params)
    df = bars.df.reset_index()
    df['timestamp'] = df['timestamp'].apply(lambda x: x.astimezone(pytz.timezone('EST'))) # Eastern Standard Time (EST) is 5 hours behind Coordinated Universal Time (UTC)
    df.drop(columns=['symbol', 'trade_count', 'vwap'], inplace=True)
    return df

In [5]:
%%time
# symbol = 'TSLA'
symbol = 'ASML'
df_symbol = fetch_pricing_data(client, symbol, datetime.datetime(2016, 11, 25, 14, 30, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 11, 25, 21, 00, tzinfo=datetime.timezone.utc))
df_symbol.head()

CPU times: user 11.5 s, sys: 10.9 s, total: 22.4 s
Wall time: 2min 34s

                  timestamp     open    high      low   close   volume
0 2016-11-25 09:30:00-05:00  103.970  103.99  103.920  103.93  30594.0
1 2016-11-25 09:31:00-05:00  103.915  103.99  103.915  103.99   5533.0
2 2016-11-25 09:32:00-05:00  103.990  104.08  103.970  104.08   4530.0
3 2016-11-25 09:33:00-05:00  104.090  104.09  104.090  104.09    133.0
4 2016-11-25 09:34:00-05:00  104.020  104.02  103.940  103.94   2444.0

### add technical indicators

In [8]:
# https://ta-lib.github.io/ta-lib-python/funcs.html
df_symbol['EMA3'] = talib.EMA(df_symbol['close'], timeperiod=3)
df_symbol['EMA5'] = talib.EMA(df_symbol['close'], timeperiod=5)
df_symbol['EMA10'] = talib.EMA(df_symbol['close'], timeperiod=10)
df_symbol['EMA15'] = talib.EMA(df_symbol['close'], timeperiod=15)
df_symbol['RSI'] = talib.RSI(df_symbol['close'], timeperiod=14)
df_symbol['MACD'], df_symbol['MACD_signal'], df_symbol['MACD_hist'] = talib.MACD(df_symbol['close'], fastperiod=12, slowperiod=26, signalperiod=9)
df_symbol['MFI'] = talib.MFI(df_symbol['high'], df_symbol['low'], df_symbol['close'], df_symbol['volume'], timeperiod=14)
df_symbol['DX'] = talib.DX(df_symbol['high'], df_symbol['low'], df_symbol['close'], timeperiod=14)

In [9]:
df_symbol.head(40)

,timestamp,open,high,low,close,volume,EMA3,EMA5,EMA10,EMA15,RSI,MACD,MACD_signal,MACD_hist,MFI,DX
0,2016-11-25 09:30:00-05:00,103.9700,103.9900,103.9200,103.9300,30594.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-11-25 09:31:00-05:00,103.9150,103.9900,103.9150,103.9900,5533.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-11-25 09:32:00-05:00,103.9900,104.0800,103.9700,104.0800,4530.0,104.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-11-25 09:33:00-05:00,104.0900,104.0900,104.0900,104.0900,133.0,104.045000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-11-25 09:34:00-05:00,104.0200,104.0200,103.9400,103.9400,2444.0,103.992500,104.006000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2016-11-25 09:35:00-05:00,103.9800,103.9800,103.8900,103.8900,2900.0,103.941250,103.967333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2016-11-25 09:36:00-05:00,103.9700,104.0400,103.9400,104.0000,3680.0,103.970625,103.978222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2016-11-25 09:37:00-05:00,104.0300,104.0600,104.0300,104.0500,2676.0,104.010312,104.002148,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2016-11-25 09:38:00-05:00,104.0600,104.1000,104.0600,104.1000,1633.0,104.055156,104.034765,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2016-11-25 09:39:00-05:00,104.1000,104.1000,104.0300,104.0400,1350.0,104.047578,104.036510,104.011000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2016-11-25 09:40:00-05:00,104.0600,104.0800,104.0600,104.0800,1120.0,104.063789,104.051007,104.023545,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2016-11-25 09:43:00-05:00,104.1400,104.1400,104.1200,104.1200,960.0,104.091895,104.074005,104.041083,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2016-11-25 09:44:00-05:00,104.0900,104.0900,104.0835,104.0835,1266.0,104.087697,104.077170,104.048795,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2016-11-25 09:45:00-05:00,104.1400,104.1400,104.0800,104.0800,557.0,104.083849,104.078113,104.054469,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2016-11-25 09:46:00-05:00,104.0800,104.0800,104.0100,104.0100,454.0,104.046924,104.055409,104.046383,104.032233,54.878049,NaN,NaN,NaN,71.227951,2.494460
15,2016-11-25 09:47:00-05:00,103.9700,104.0000,103.9600,103.9800,2030.0,104.013462,104.030273,104.034314,104.025704,52.797834,NaN,NaN,NaN,59.428159,10.188536
16,2016-11-25 09:48:00-05:00,103.9750,104.0100,103.9750,104.0100,1740.0,104.011731,104.023515,104.029893,104.023741,54.649146,NaN,NaN,NaN,54.491741,8.347090
17,2016-11-25 09:49:00-05:00,104.0200,104.0900,104.0200,104.0800,1341.0,104.045866,104.042343,104.039003,104.030774,58.717726,NaN,NaN,NaN,56.768934,5.289219
18,2016-11-25 09:50:00-05:00,104.0400,104.0800,104.0400,104.0650,500.0,104.055433,104.049896,104.043730,104.035052,57.526744,NaN,NaN,NaN,61.734560,5.289219
19,2016-11-25 09:51:00-05:00,104.1100,104.1100,104.1100,104.1100,101.0,104.082716,104.069930,104.055779,104.044420,60.138855,NaN,NaN,NaN,71.147708,10.204354
20,2016-11-25 09:52:00-05:00,104.0800,104.0800,104.0700,104.0700,250.0,104.076358,104.069954,104.058365,104.047618,56.795212,NaN,NaN,NaN,63.392833,2.561692
21,2016-11-25 09:53:00-05:00,104.0200,104.0200,104.0200,104.0200,200.0,104.048179,104.053302,104.051389,104.044166,52.840403,NaN,NaN,NaN,55.199228,6.195489
22,2016-11-25 09:54:00-05:00,104.0300,104.0400,103.9000,104.0300,19402.0,104.039090,104.045535,104.047500,104.042395,53.537243,NaN,NaN,NaN,18.617011,23.154276
23,2016-11-25 09:55:00-05:00,103.9900,103.9900,103.9900,103.9900,100.0,104.014545,104.027023,104.037046,104.035846,50.333448,NaN,NaN,NaN,19.392567,23.154276
24,2016-11-25 09:56:00-05:00,104.0050,104.0300,104.0050,104.0300,1244.0,104.022272,104.028016,104.035765,104.035115,53.340452,NaN,NaN,NaN,19.722698,15.109216
25,2016-11-25 09:57:00-05:00,104.0100,104.0100,103.9900,103.9900,223.0,104.006136,104.015344,104.027444,104.029475,50.075478,NaN,NaN,NaN,16.949473,17.291180
26,2016-11-25 09:58:00-05:00,104.0050,104.0200,103.9900,104.0100,1422.0,104.008068,104.013562,104.024272,104.027041,51.668451,NaN,NaN,NaN,21.670767,15.165957
27,2016-11-25 09:59:00-05:00,104.0100,104.0100,104.0000,104.0000,791.0,104.004034,104.009042,104.019859,104.023661,50.795728,NaN,NaN,NaN,19.629886,15.165957
28,2016-11-25 10:00:00-05:00,103.9800,103.9800,103.9800,103.9800,407.0,103.992017,103.999361,104.012612,104.018203,49.012636,NaN,NaN,NaN,19.661046,18.587558
29,2016-11-25 10:01:00-05:00,103.9800,103.9800,103.9500,103.9500,410.0,103.971009,103.982907,104.001228,104.009678,46.382509,NaN,NaN,NaN,20.793131,23.567380
30,2016-11-25 10:02:00-05:00,104.0000,104.0000,103.9400,103.9700,4206.0,103.970504,103.978605,103.995550,104.004718,48.371583,NaN,NaN,NaN,27.174147,18.369155
31,2016-11-25 10:03:00-05:00,103.9700,103.9900,103.9600,103.9900,1550.0,103.980252,103.982403,103.994541,104.002878,50.354958,NaN,NaN,NaN,27.665633,18.369155
32,2016-11-25 10:04:00-05:00,104.0000,104.0000,103.9700,103.9700,938.0,103.975126,103.978269,103.990079,103.998769,48.354464,NaN,NaN,NaN,28.122387,15.550371
33,2016-11-25 10:05:00-05:00,103.9600,103.9800,103.9400,103.9400,436.0,103.957563,103.965513,103.980974,103.991423,45.438418,-0.019043,-0.010334,-0.008709,27.485161,21.583424
34,2016-11-25 10:06:00-05:00,103.9800,103.9800,103.9700,103.9800,1400.0,103.968782,103.970342,103.980797,103.989995,49.786536,-0.018158,-0.011899,-0.006259,30.894517,21.583424
35,2016-11-25 10:07:00-05:00,104.0100,104.0100,104.0100,104.0100,230.0,103.989391,103.983561,103.986106,103.992495,52.823148,-0.014865,-0.012492,-0.002373,31.588350,12.280625
36,2016-11-25 10:08:00-05:00,103.9700,103.9700,103.9700,103.9700,100.0,103.979695,103.979041,103.983178,103.989683,48.602751,-0.015307,-0.013055,-0.002252,80.294564,20.963984
37,2016-11-25 10:09:00-05:00,103.9500,103.9700,103.9500,103.9500,517.0,103.964848,103.969361,103.977146,103.984723,46.598041,-0.017074,-0.013859,-0.003215,77.707074,24.963605
38,2016-11-25 10:10:00-05:00,103.9000,103.9100,103.9000,103.9100,400.0,103.937424,103.949574,103.964937,103.975383,42.796067,-0.021455,-0.015378,-0.006077,72.843827,33.961040
39,2016-11-25 10:15:00-05:00,103.9375,103.9375,103.9200,103.9200,352.0,103.928712,103.939716,103.956767,103.968460,44.025643,-0.023844,-0.017071,-0.006773,74.955118,25.077743

In [77]:
df_symbol.iloc[33:].to_csv(f'./{symbol}.csv', index=False)

In [10]:
df_market = fetch_pricing_data(client, 'QQQ', df_symbol['timestamp'].iloc[0], df_symbol['timestamp'].iloc[-1])
df_market.head()

                  timestamp      open     high     low   close    volume
0 2016-11-25 09:30:00-05:00  118.5700  118.650  118.56  118.60  287813.0
1 2016-11-25 09:31:00-05:00  118.6000  118.610  118.47  118.48  105250.0
2 2016-11-25 09:32:00-05:00  118.5200  118.570  118.49  118.57   71296.0
3 2016-11-25 09:33:00-05:00  118.5781  118.593  118.50  118.56   93718.0
4 2016-11-25 09:34:00-05:00  118.5600  118.560  118.43  118.46   44941.0

In [11]:
df_market.iloc[33:].to_csv(f'./QQQ.csv', index=False)

## fetch Alpaca's news data

In [81]:
def clean_text(text):
    # remove HTML tags using BeautifulSoup
    text_no_html = BeautifulSoup(text, 'html.parser').get_text(separator=' ')
    # remove URLs
    text_no_urls = re.sub(r'http\S+', '', text_no_html)
    # additional cleanup if needed (like removing Markdown or special characters)
    text_clean = re.sub(r'\[.*?\]\(.*?\)', '', text_no_urls)
    return text_clean

In [90]:
# https://docs.alpaca.markets/reference/news-1
url = "https://data.alpaca.markets/v1beta1/news?start=2016-11-25T14%3A30%3A00Z&end=2023-11-25T21%3A00%3A00Z&sort=asc&symbols=ASML&limit=50&include_content=true"
headers = {
    "accept": "application/json",
    "APCA-API-KEY-ID": API_KEY,
    "APCA-API-SECRET-KEY": API_SECRET
}

df_news = pd.DataFrame(columns=['text', 'timestamp'])
num_page = 1
response = json.loads(requests.get(url, headers=headers).text)
for news in response['news']:
    df_news.loc[len(df_news)] = [clean_text('\n'.join([news['headline'], news['summary'], news['content']])), news['created_at']]
print(f"page num: {num_page}; news num: {len(response['news'])}")
        
while response['next_page_token'] is not None:
    response = json.loads(requests.get(url + f"&page_token={response['next_page_token']}", headers=headers).text)
    num_page += 1
    for news in response['news']:
        df_news.loc[len(df_news)] = [clean_text(news['headline'] + '.' + news['content']), news['created_at']]
    print(f"page num: {num_page}; news num: {len(response['news'])}")

/var/folders/w3/fw0vkmx53s91mn8q96w593l80000gn/T/ipykernel_51195/1543417829.py:3: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  text_no_html = BeautifulSoup(text, 'html.parser').get_text(separator=' ')

page num: 1; news num: 50
page num: 2; news num: 50
page num: 3; news num: 50
page num: 4; news num: 50
page num: 5; news num: 50
page num: 6; news num: 50
page num: 7; news num: 50
page num: 8; news num: 50
page num: 9; news num: 50
page num: 10; news num: 50
page num: 11; news num: 50
page num: 12; news num: 50
page num: 13; news num: 50
page num: 14; news num: 30

/var/folders/w3/fw0vkmx53s91mn8q96w593l80000gn/T/ipykernel_51195/1543417829.py:3: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  text_no_html = BeautifulSoup(text, 'html.parser').get_text(separator=' ')

In [91]:
df_news['timestamp'] = pd.to_datetime(df_news['timestamp']).apply(lambda x: x.astimezone(pytz.timezone('EST')))
display(df_news.head())
df_news.shape

                                                text                 timestamp
0  18 Stocks Moving In Monday's Pre-Market Sessio... 2016-12-05 08:29:19-05:00
1  Bank of America Upgrades ASML Holding N.V. to ... 2016-12-19 06:32:08-05:00
2  Benzinga's Top Upgrades, Downgrades For Januar... 2017-01-17 09:22:35-05:00
3  Earnings Scheduled For January 18, 2017\n\n \r... 2017-01-18 04:33:08-05:00
4  ASML +4.3% Premarket @$120.91; CFO Says 2017 i... 2017-01-18 07:55:31-05:00

(680, 2)

In [92]:
df_news.to_csv(f'./{symbol}_news.csv', index=False)

In [85]:
df_news.tail()

,text,datetime
675,"""ASML To Invest €100 Million A Year In Berlin ...",2023-11-20 15:22:59-05:00
676,$1000 Invested In This Stock 5 Years Ago Would...,2023-11-21 09:00:16-05:00
677,Decoding ASML Holding's Options Activity: What...,2023-11-21 15:45:48-05:00
678,Dutch Stocks Nudge Upward On Thanksgiving Afte...,2023-11-23 12:03:07-05:00
679,Evaluating ASML Holding Against Peers In Semic...,2023-11-24 11:00:28-05:00

## explore Alpha Vantage's sentiment data (in limited time range)

In [86]:
# https://www.alphavantage.co/documentation/#news-sentiment
url = 'https://www.alphavantage.co/query?function=NEWS_SENTIMENT&tickers=ASML&time_from=20161125T0930&time_to=20231126T0930&apikey=xLwN8xZRExYWeGLJiGyQ&limit=1000&sort=EARLIEST'
r = requests.get(url)
data = r.json()

data

{'items': '674',
 'sentiment_score_definition': 'x <= -0.35: Bearish; -0.35 < x <= -0.15: Somewhat-Bearish; -0.15 < x < 0.15: Neutral; 0.15 <= x < 0.35: Somewhat_Bullish; x >= 0.35: Bullish',
 'relevance_score_definition': '0 < x <= 1, with a higher score indicating higher relevance.',
 'feed': [{'title': 'These 2 Nasdaq Stocks Could Carry Your Portfolio for Years',
   'url': 'https://www.fool.com/investing/2022/03/09/these-2-nasdaq-stocks-could-carry-your-portfolio-f/',
   'time_published': '20220309T111100',
   'authors': ['Harsh Chauhan'],
   'summary': 'The sell-off in these stocks gives investors the opportunity to buy two solid companies for the long run.',
   'banner_image': 'https://media.ycharts.com/charts/881eb905b73ca409f1841bc7e20fce43.png',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'Economy - Monetary', 'relevance_score': '0.310843'},
    {'topic': 'Retail & Wholesale', 'relevance_score': '0.333333'},
    {'topic': 'Financial Markets', 'relevance_score': '0.962106'},
    {'topic': 'Manufacturing', 'relevance_score': '0.333333'},
    {'topic': 'Earnings', 'relevance_score': '1.0'},
    {'topic': 'Technology', 'relevance_score': '0.333333'}],
   'overall_sentiment_score': 0.126561,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'ATVI',
     'relevance_score': '0.03533',
     'ticker_sentiment_score': '0.12479',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'MSFT',
     'relevance_score': '0.43526',
     'ticker_sentiment_score': '0.286545',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'SSNLF',
     'relevance_score': '0.03533',
     'ticker_sentiment_score': '0.06824',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'AMZN',
     'relevance_score': '0.03533',
     'ticker_sentiment_score': '0.020274',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'INTC',
     'relevance_score': '0.03533',
     'ticker_sentiment_score': '0.06824',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'ASML',
     'relevance_score': '0.342187',
     'ticker_sentiment_score': '-0.023962',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'Benchmark Lists Impact Of Russia-Ukraine Crisis On Semiconductor Industry',
   'url': 'https://www.benzinga.com/news/22/03/26084173/benchmark-lists-impact-of-russia-ukraine-crisis-on-semiconductor-industry',
   'time_published': '20220310T171838',
   'authors': [],
   'summary': 'Benchmark analyst Mark Miller observed how the Russia -Ukraine crisis affected the semiconductor manufacturing industry.\nCoherent Inc  ( NASDAQ: COHR )  and MKS Instruments Inc  ( NASDAQ: MKSI )   ( MKS )  felt the pinch as gas lasers producers, which play an essential role in semiconductor manufact',
   'banner_image': 'https://cdn.benzinga.com/files/imagecache/og_image_social_share_1200x630/images/story/2012/abtech_3715.png',
   'source': 'Benzinga',
   'category_within_source': 'News',
   'source_domain': 'www.benzinga.com',
   'topics': [{'topic': 'Life Sciences', 'relevance_score': '0.5'},
    {'topic': 'Technology', 'relevance_score': '0.5'}],
   'overall_sentiment_score': -0.114751,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'MKSI',
     'relevance_score': '0.773129',
     'ticker_sentiment_score': '0.048885',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'COHR',
     'relevance_score': '0.635246',
     'ticker_sentiment_score': '0.065981',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'ASML',
     'relevance_score': '0.454309',
     'ticker_sentiment_score': '-0.437728',
     'ticker_sentiment_label': 'Bearish'}]},
  {'title': 'Should You Invest in the VanEck Semiconductor ETF  ( SMH ) ?',
   'url': 'https://www.zacks.com/stock/news/1881376/should-you-invest-in-the-vaneck-semiconductor-etf-smh',
   'time_published': '20220314T102007',
   'authors': ['Zacks Investment Research'],
   'summary': 'Sector ETF report for SMH',
   'banner_image': 'https://staticx-tuner.zacks.com/images/default_article_images/default224.jpg',
   'source': 'Zacks Commentary',
   'category_within_source': 'n/a',
   'source_domain': 'www.zacks.com',
   'topics': [{'topic': 'Technology', 'relevance_score': '0.5'},
    {'topic': 'Financial Markets', 'relevance_score': '0.999998'},
    {'topic': 'Manufacturing', 'relevance_score': '0.5'}],
   'overall_sentiment_score': 0.093149,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'NVDA',
     'relevance_score': '0.133285',
     'ticker_sentiment_score': '0.001401',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'ASML',
     'relevance_score': '0.133285',
     'ticker_sentiment_score': '0.001401',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'TSM',
     'relevance_score': '0.133285',
     'ticker_sentiment_score': '0.001401',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': '3 Stocks That Could Soon Split Other Than Amazon',
   'url': 'https://www.fool.com/investing/2022/03/14/3-stocks-that-could-soon-split-other-than-amazon/',
   'time_published': '20220314T110000',
   'authors': ['Anders Bylund', 'Nicholas Rossolillo', 'and Billy Duberstein'],
   'summary': "Amazon's 20-for-1 stock split is making headlines. One day, these other stocks could, too.",
   'banner_image': 'https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Feditorial%2Fimages%2F670139%2Finvesting-children-building-wealth.jpg&w=700&op=resize',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'Economy - Monetary', 'relevance_score': '0.310843'},
    {'topic': 'Financial Markets', 'relevance_score': '0.922939'},
    {'topic': 'Manufacturing', 'relevance_score': '0.333333'},
    {'topic': 'Earnings', 'relevance_score': '0.614606'},
    {'topic': 'Technology', 'relevance_score': '0.333333'},
    {'topic': 'Finance', 'relevance_score': '0.333333'}],
   'overall_sentiment_score': -0.026241,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'SIVB',
     'relevance_score': '0.154217',
     'ticker_sentiment_score': '-0.078902',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'ASML',
     'relevance_score': '0.359361',
     'ticker_sentiment_score': '-0.235884',
     'ticker_sentiment_label': 'Somewhat-Bearish'},
    {'ticker': 'AVGO',
     'relevance_score': '0.244354',
     'ticker_sentiment_score': '-0.158532',
     'ticker_sentiment_label': 'Somewhat-Bearish'}]},
  {'title': 'ASML reports transactions under its current share buyback program',
   'url': 'https://www.globenewswire.com/news-release/2022/03/14/2402738/0/en/ASML-reports-transactions-under-its-current-share-buyback-program.html',
   'time_published': '20220314T141200',
   'authors': ['ASML Netherlands BV'],
   'summary': "VELDHOVEN, the Netherlands - ASML Holding N.V.  ( ASML )  reports the following transactions, conducted under ASML's current share buyback program.",
   'banner_image': 'https://ml-eu.globenewswire.com/Resource/Download/0e922787-0d4f-4763-99ed-f3c70bdc20b1?size=1',
   'source': 'GlobeNewswire',
   'category_within_source': 'n/a',
   'source_domain': 'www.globenewswire.com',
   'topics': [{'topic': 'Technology', 'relevance_score': '1.0'}],
   'overall_sentiment_score': 0.001333,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'ASML',
     'relevance_score': '0.820495',
     'ticker_sentiment_score': '0.001333',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'ASML publishes agenda Annual General Meeting 2022',
   'url': 'https://www.globenewswire.com/news-release/2022/03/15/2403049/0/en/ASML-publishes-agenda-Annual-General-Meeting-2022.html',
   'time_published': '20220315T070000',
   'authors': ['ASML Netherlands BV'],
   'summary': 'ASML publishes agenda Annual General Meeting 2022Reappointment of Board of Management members and changes in Supervisory Board announced',
   'banner_image': 'https://ml-eu.globenewswire.com/Resource/Download/0e922787-0d4f-4763-99ed-f3c70bdc20b1?size=1',
   'source': 'GlobeNewswire',
   'category_within_source': 'n/a',
   'source_domain': 'www.globenewswire.com',
   'topics': [{'topic': 'Technology', 'relevance_score': '0.5'},
    {'topic': 'Manufacturing', 'relevance_score': '0.5'}],
   'overall_sentiment_score': 0.145073,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'BCNAF',
     'relevance_score': '0.055686',
     'ticker_sentiment_score': '0.048875',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'UMICF',
     'relevance_score': '0.055686',
     'ticker_sentiment_score': '0.048875',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'ASML',
     'relevance_score': '0.598073',
     'ticker_sentiment_score': '0.185774',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'NXPI',
     'relevance_score': '0.055686',
     'ticker_sentiment_score': '0.048875',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': "Here's How Much $100 Invested In ASML Holding 10 Years Ago Would Be Worth Today",
   'url': 'https://www.benzinga.com/news/earnings/22/03/26145534/heres-how-much-100-invested-in-asml-holding-10-years-ago-would-be-worth-today',
   'time_published': '20220315T141625',
   'authors': [],
   'summary': 'ASML Holding  ( NASDAQ:ASML )  has outperformed the market over the past 10 years by 13.42% on an annualized basis. \nBuying $100 In ASML: 10 years ago, an investor could have purchased 1.59 shares of ASML Holding at the time with $100. This investment ...Full story available on Benzinga.com',
   'banner_image': 'https://cdn.benzinga.com/files/images/story/2022/1647352920_0.png',
   'source': 'Benzinga',
   'category_within_source': 'News',
   'source_domain': 'www.benzinga.com',
   'topics': [{'topic': 'Technology', 'relevance_score': '1.0'}],
   'overall_sentiment_score': 0.043718,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'ASML',
     'relevance_score': '0.982732',
     'ticker_sentiment_score': '0.043718',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': "China's Hikvision to kick-start chip production with used ASML equipment",
   'url': 'https://www.scmp.com/tech/tech-war/article/3170691/us-china-tech-war-chinese-surveillance-camera-maker-hikvision-acquire',
   'time_published': '20220316T133013',
   'authors': ['Che Pan'],
   'summary': "Hangzhou Hikvision Digital Technology, one of the world's largest suppliers of video surveillance cameras, plans to buy a second-hand lithography machine made by Dutch firm ASML Holding for its in-house chip manufacturing operation, according to a source familiar with the matter, marking a big move ",
   'banner_image': 'https://img.i-scmp.com/cdn-cgi/image/fit=contain,width=425,format=auto/sites/default/files/styles/768x768/public/d8/images/canvas/2022/03/16/ebec8e34-bee0-422c-b465-c3dc264e61e9_7233dfca.jpg?itok=QqEu1WUE&v=1647425361',
   'source': 'South China Morning Post',
   'category_within_source': 'Money',
   'source_domain': 'www.scmp.com',
   'topics': [{'topic': 'Earnings', 'relevance_score': '0.614606'},
    {'topic': 'Economy - Fiscal', 'relevance_score': '0.158519'},
    {'topic': 'Technology', 'relevance_score': '1.0'}],
   'overall_sentiment_score': -0.003522,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'ASML',
     'relevance_score': '0.352342',
     'ticker_sentiment_score': '0.0245',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'SZIHF',
     'relevance_score': '0.052056',
     'ticker_sentiment_score': '-0.616017',
     'ticker_sentiment_label': 'Bearish'}]},
  {'title': 'Goldman Sachs Upgraded ASML To Conviction Buy - Read Why',
   'url': 'https://www.benzinga.com/analyst-ratings/analyst-color/22/03/26196351/goldman-sachs-upgraded-asml-to-conviction-buy-read-why',
   'time_published': '20220318T102441',
   'authors': [],
   'summary': 'Goldman Sachs analyst Alexander Duval upgraded ASML Holding NV  ( NASDAQ: ASML )  to Conviction Buy from Buy with a €930 price target  ( 57.20% upside ) . \nDuval sees ASML as a "core Digital Enabler" given its monopoly position on Extreme Ultraviolet Lithography.\nASML\'s de-rating from 29-times price',
   'banner_image': 'https://cdn.benzinga.com/files/imagecache/og_image_social_share_1200x630/images/story/2012/abtech_3819.png',
   'source': 'Benzinga',
   'category_within_source': 'News',
   'source_domain': 'www.benzinga.com',
   'topics': [{'topic': 'Earnings', 'relevance_score': '0.360215'},
    {'topic': 'Technology', 'relevance_score': '0.5'},
    {'topic': 'Finance', 'relevance_score': '0.5'}],
   'overall_sentiment_score': -0.011804,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'GS',
     'relevance_score': '0.30355',
     'ticker_sentiment_score': '0.000353',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'ASML',
     'relevance_score': '0.980752',
     'ticker_sentiment_score': '-0.039225',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'Jefferies Lists Preferred Semiconductor Capital Equipment Stocks',
   'url': 'https://www.benzinga.com/news/22/03/26198886/jefferies-lists-preferred-semiconductor-capital-equipment-stocks',
   'time_published': '20220318T122748',
   'authors': [],
   'summary': "Jefferies analyst Mark Lipacis' analysis of transistor count in CPUs supported his thesis of secular demand for wafer fab equipment.\nCPU die sizes have increased by 5x - 9x for Intel Corp  ( NASDAQ: INTC )  and Apple Inc  ( NASDAQ: AAPL )  over three to five years. \nHe views the current risk-reward ",
   'banner_image': 'https://cdn.benzinga.com/files/imagecache/og_image_social_share_1200x630/images/story/2012/abtech_3826.png',
   'source': 'Benzinga',
   'category_within_source': 'News',
   'source_domain': 'www.benzinga.com',
   'topics': [{'topic': 'Life Sciences', 'relevance_score': '0.333333'},
    {'topic': 'Technology', 'relevance_score': '0.333333'},
    {'topic': 'Manufacturing', 'relevance_score': '0.333333'}],
   'overall_sentiment_score': -0.015783,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'KLAC',
     'relevance_score': '0.515636',
     'ticker_sentiment_score': '0.017478',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'AMAT',
     'relevance_score': '0.515636',
     'ticker_sentiment_score': '0.017478',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'AAPL',
     'relevance_score': '0.515636',
     'ticker_sentiment_score': '0.051044',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'INTC',
     'relevance_score': '0.515636',
     'ticker_sentiment_score': '0.051044',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'LRCX',
     'relevance_score': '0.515636',
     'ticker_sentiment_score': '0.017478',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'ACMR',
     'relevance_score': '0.515636',
     'ticker_sentiment_score': '0.017478',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'ASML',
     'relevance_score': '0.705799',
     'ticker_sentiment_score': '0.012672',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': "ASML Chief Warns Critical Equipment Crisis Is Dampening Chipmakers' Ambitious Expansion Plans: FT",
   'url': 'https://www.benzinga.com/news/22/03/26215603/asml-chief-warns-critical-equipment-crisis-is-dampening-chipmakers-ambitious-expansion-plans-ft',
   'time_published': '20220321T111434',
   'authors': [],
   'summary': "ASML Holding NV  ( NASDAQ: ASML )  CEO Peter Wennink warned about the critical equipment crisis as the supply chains struggled to drive production, the Financial Times reports.\nWennink saw the crisis impeding chipmakers' multibillion-dollar expansion plans over the next two years, \nIntel Corp  ( NAS",
   'banner_image': 'https://cdn.benzinga.com/files/imagecache/og_image_social_share_1200x630/images/story/2012/abtech_3841.png',
   'source': 'Benzinga',
   'category_within_source': 'News',
   'source_domain': 'www.benzinga.com',
   'topics': [{'topic': 'Technology', 'relevance_score': '0.5'},
    {'topic': 'Manufacturing', 'relevance_score': '0.5'}],
   'overall_sentiment_score': -0.163749,
   'overall_sentiment_label': 'Somewhat-Bearish',
   'ticker_sentiment': [{'ticker': 'INTC',
     'relevance_score': '0.436009',
     'ticker_sentiment_score': '-0.261761',
     'ticker_sentiment_label': 'Somewhat-Bearish'},
    {'ticker': 'ASML',
     'relevance_score': '0.436009',
     'ticker_sentiment_score': '-0.195814',
     'ticker_sentiment_label': 'Somewhat-Bearish'},
    {'ticker': 'TSM',
     'relevance_score': '0.436009',
     'ticker_sentiment_score': '-0.011968',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'Morning Brief: Top Stories Dominating Financial Media on Monday, March 21',
   'url': 'https://www.benzinga.com/news/22/03/26217302/morning-brief-top-stories-dominating-financial-media-on-monday-march-21',
   'time_published': '20220321T120503',
   'authors': [],
   'summary': 'CNBC\nHealth Experts Forecast Increase In COVID-19 Cases In US Amid New Omicron Subvariant\nU.S. health experts warn that an emerging, highly contagious COVID-19 omicron variant, BA.2, could soon increase domestic coronavirus cases.\nWhite House chief medical advisor Dr. Anthony Fauci said on ABC\'s "Th',
   'banner_image': 'https://cdn.benzinga.com/files/imagecache/og_image_social_share_1200x630/images/story/2012/nyse_trading_floor-wikimedia_7.jpg',
   'source': 'Benzinga',
   'category_within_source': 'News',
   'source_domain': 'www.benzinga.com',
   'topics': [{'topic': 'Life Sciences', 'relevance_score': '0.2'},
    {'topic': 'Energy & Transportation', 'relevance_score': '0.2'},
    {'topic': 'Technology', 'relevance_score': '0.2'},
    {'topic': 'Finance', 'relevance_score': '0.2'},
    {'topic': 'Blockchain', 'relevance_score': '0.158519'},
    {'topic': 'IPO', 'relevance_score': '0.310843'},
    {'topic': 'Financial Markets', 'relevance_score': '0.918141'},
    {'topic': 'Manufacturing', 'relevance_score': '0.2'}],
   'overall_sentiment_score': -0.05985,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'BB',
     'relevance_score': '0.106778',
     'ticker_sentiment_score': '0.0211',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'C',
     'relevance_score': '0.071304',
     'ticker_sentiment_score': '-0.006414',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'BAC',
     'relevance_score': '0.071304',
     'ticker_sentiment_score': '-0.006414',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'JPM',
     'relevance_score': '0.071304',
     'ticker_sentiment_score': '-0.006414',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'MS',
     'relevance_score': '0.071304',
     'ticker_sentiment_score': '-0.006414',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'LDNXF',
     'relevance_score': '0.035688',
     'ticker_sentiment_score': '0.001368',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'GS',
     'relevance_score': '0.071304',
     'ticker_sentiment_score': '-0.006414',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'PLAN',
     'relevance_score': '0.106778',
     'ticker_sentiment_score': '0.00715',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'CP',
     'relevance_score': '0.071304',
     'ticker_sentiment_score': '-0.134042',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'ASML',
     'relevance_score': '0.071304',
     'ticker_sentiment_score': '-0.163746',
     'ticker_sentiment_label': 'Somewhat-Bearish'},
    {'ticker': 'DIS',
     'relevance_score': '0.071304',
     'ticker_sentiment_score': '-0.152187',
     'ticker_sentiment_label': 'Somewhat-Bearish'},
    {'ticker': 'AZN',
     'relevance_score': '0.071304',
     'ticker_sentiment_score': '0.004762',
     'ticker_sentiment_label': 'Neutral'},

In [87]:
data.keys()

dict_keys(['items', 'sentiment_score_definition', 'relevance_score_definition', 'feed'])

In [88]:
data['feed'][-1]

{'title': 'VEA: Is Vanguard FTSE Developed Markets ETF  ( VEA )  a Solid Buy?',
 'url': 'https://stocknews.com/news/vea-dbeu-hezu-eden-asml-is-vanguard-ftse-developed-markets-etf-vea-a-solid-buy/',
 'time_published': '20230825T155221',
 'authors': ['StockNews.com Staff'],
 'summary': "The three primary U.S. stock indices closed with losses exceeding 1% each on Thursday, and investor apprehension loomed as they awaited Federal Reserve Chair Jerome Powell's speech scheduled for today.",
 'banner_image': 'https://stocknews.com/wp-content/uploads/2022/06/ETF_iSto_FB.jpg',
 'source': 'Stocknews.com',
 'category_within_source': 'n/a',
 'source_domain': 'stocknews.com',
 'topics': [{'topic': 'Economy - Monetary', 'relevance_score': '0.451494'},
  {'topic': 'Life Sciences', 'relevance_score': '0.5'},
  {'topic': 'Financial Markets', 'relevance_score': '0.999862'},
  {'topic': 'Technology', 'relevance_score': '0.5'}],
 'overall_sentiment_score': 0.125507,
 'overall_sentiment_label': 'Neutral',
 'ticker_sentiment': [{'ticker': 'SSNLF',
   'relevance_score': '0.053035',
   'ticker_sentiment_score': '0.046993',
   'ticker_sentiment_label': 'Neutral'},
  {'ticker': 'NSRGF',
   'relevance_score': '0.053035',
   'ticker_sentiment_score': '0.046993',
   'ticker_sentiment_label': 'Neutral'},
  {'ticker': 'NVO',
   'relevance_score': '0.053035',
   'ticker_sentiment_score': '0.046993',
   'ticker_sentiment_label': 'Neutral'},
  {'ticker': 'ASML',
   'relevance_score': '0.105836',
   'ticker_sentiment_score': '0.051845',
   'ticker_sentiment_label': 'Neutral'}]}

In [89]:
data['feed'][-1]

{'title': 'VEA: Is Vanguard FTSE Developed Markets ETF  ( VEA )  a Solid Buy?',
 'url': 'https://stocknews.com/news/vea-dbeu-hezu-eden-asml-is-vanguard-ftse-developed-markets-etf-vea-a-solid-buy/',
 'time_published': '20230825T155221',
 'authors': ['StockNews.com Staff'],
 'summary': "The three primary U.S. stock indices closed with losses exceeding 1% each on Thursday, and investor apprehension loomed as they awaited Federal Reserve Chair Jerome Powell's speech scheduled for today.",
 'banner_image': 'https://stocknews.com/wp-content/uploads/2022/06/ETF_iSto_FB.jpg',
 'source': 'Stocknews.com',
 'category_within_source': 'n/a',
 'source_domain': 'stocknews.com',
 'topics': [{'topic': 'Economy - Monetary', 'relevance_score': '0.451494'},
  {'topic': 'Life Sciences', 'relevance_score': '0.5'},
  {'topic': 'Financial Markets', 'relevance_score': '0.999862'},
  {'topic': 'Technology', 'relevance_score': '0.5'}],
 'overall_sentiment_score': 0.125507,
 'overall_sentiment_label': 'Neutral',
 'ticker_sentiment': [{'ticker': 'SSNLF',
   'relevance_score': '0.053035',
   'ticker_sentiment_score': '0.046993',
   'ticker_sentiment_label': 'Neutral'},
  {'ticker': 'NSRGF',
   'relevance_score': '0.053035',
   'ticker_sentiment_score': '0.046993',
   'ticker_sentiment_label': 'Neutral'},
  {'ticker': 'NVO',
   'relevance_score': '0.053035',
   'ticker_sentiment_score': '0.046993',
   'ticker_sentiment_label': 'Neutral'},
  {'ticker': 'ASML',
   'relevance_score': '0.105836',
   'ticker_sentiment_score': '0.051845',
   'ticker_sentiment_label': 'Neutral'}]}