In [1]:
!pip install --upgrade accelerate
!pip install --upgrade bitsandbytes
!pip install --upgrade peft
!pip install --upgrade sentencepiece
!pip install --upgrade transformers

Collecting accelerate
  Downloading accelerate-0.25.0-py3-none-any.whl (265 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 265.7/265.7 kB 2.8 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from accelerate) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from accelerate) (23.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from accelerate) (6.0.1)
Requirement already satisfied: torch>=1.10.0 in /usr/local/lib/python3.10/dist-packages (from accelerate) (2.1.0+cu118)
Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.10/dist-packages (from accelerate) (0.19.4)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from accelerate) (0.4.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (3.13.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (4.5.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (3.2.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (3.1.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (2023.6.0)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (2.1.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub->accelerate) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub->accelerate) (4.66.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.10.0->accelerate) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub->accelerate) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub->accelerate) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub->accelerate) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub->accelerate) (2023.11.17)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.10.0->accelerate) (1.3.0)
Installing collected packages: accelerate
Successfully installed accelerate-0.25.0
Collecting bitsandbytes
  Downloading bitsandbytes-0.41.2.post2-py3-none-any.whl (92.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.6/92.6 MB 11.5 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.41.2.post2
Collecting peft
  Downloading peft-0.6.2-py3-none-any.whl (174 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 174.7/174.7 kB 1.9 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from peft) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from peft) (23.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from peft) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from peft) (6.0.1)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.10/dist-packages (from peft) (2.1.0+cu118)
Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (from peft) (4.35.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from peft) (4.66.1)
Requirement already satisfied: accelerate>=0.21.0 in /usr/local/lib/python3.10/dist-packages (from peft) (0.25.0)
Requirement already satisfied: safetensors in /usr/local/lib/python3.10/dist-packages (from peft) (0.4.1)
Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.10/dist-packages (from accelerate>=0.21.0->peft) (0.19.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.13.0->peft) (3.13.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch>=1.13.0->peft) (4.5.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.13.0->peft) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.13.0->peft) (3.2.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.13.0->peft) (3.1.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=1.13.0->peft) (2023.6.0)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.13.0->peft) (2.1.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers->peft) (2023.6.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers->peft) (2.31.0)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers->peft) (0.15.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.13.0->peft) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers->peft) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers->peft) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers->peft) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers->peft) (2023.11.17)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.13.0->peft) (1.3.0)
Installing collected packages: peft
Successfully installed peft-0.6.2
Collecting sentencepiece
  Downloading sentencepiece-0.1.99-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 7.0 MB/s eta 0:00:00
Installing collected packages: sentencepiece
Successfully installed sentencepiece-0.1.99
Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.35.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.13.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.19.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2023.6.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.31.0)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.15.0)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.4.1)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.66.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.16.4->transformers) (2023.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.16.4->transformers) (4.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2023.11.17)

In [2]:
import csv
import gc
import re

from bs4 import BeautifulSoup
import pandas as pd
from peft import PeftModel
from transformers import AutoModel, AutoTokenizer, AutoModelForCausalLM, BertTokenizer, LlamaForCausalLM, LlamaTokenizerFast, pipeline
import torch
from tqdm import tqdm
from google.colab import drive

In [7]:
test_text = "ASML Holding's Q3 Earnings Preview\n\n ASML Holding  (NASDAQ: ASML ) announces its next round of earnings this Wednesday. Here is Benzinga's everything-that-matters guide for the\xa0Q3 earnings announcement. \n Earnings and Revenue \n ASML Holding EPS is expected to be around $1.82, according to sell-side analysts. Sales will likely be near $3.21 billion. \n In the same quarter last year, ASML Holding reported EPS of $1.52 on revenue of $2.89 billion. If the company were to match the consensus estimate when it reports Wednesday, EPS would be up 19.74 percent. Revenue would be up 11.15 percent from the same quarter last year. Here's how the company's reported EPS has compared to analyst estimates in the past: \n \xa0 \n \n \n \n Quarter \n Q2 2018 \n Q1 2018 \n Q4 2017 \n Q3 2017 \n \n \n EPS Estimate \n 1.29 \n 1.13 \n 1.29 \n 1.29 \n \n \n EPS Actual \n 1.59 \n 1.56 \n 1.82 \n 1.52 \n \n \n \n Stock Performance \n Over the past 52-week period, shares of ASML Holding have declined 1.67 percent. Analysts\xa0have adjusted their estimates higher for EPS and revenues over the past 90 days. Analysts generally rate ASML Holding stock as Neutral. The strength of this rating has maintained conviction over the past three months. \n Conference Call \n ASML Holding's Q3 conference call is scheduled to begin at 8:00 a.m. ET and can be accessed here:   \n"

In [63]:
pipe = pipeline("text-classification", model="yiyanghkust/finbert-tone")
tokenizer = BertTokenizer.from_pretrained('yiyanghkust/finbert-tone')
pipe(test_text)

[{'label': 'Neutral', 'score': 0.5125790238380432}]

In [62]:
# Another LLM worth trying but not as good
pipe_2 = pipeline("text-classification", model="mrm8488/distilroberta-finetuned-financial-news-sentiment-analysis")
pipe_2(test_text)
# tokenizer = AutoTokenizer.from_pretrained("mrm8488/distilroberta-finetuned-financial-news-sentiment-analysis")

config.json:   0%|          | 0.00/933 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/328M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/333 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

[{'label': 'positive', 'score': 0.9996575117111206}]

In [3]:
df_news = pd.read_csv('ASML_news.csv')
df_news.head()

,text,datetime
0,18 Stocks Moving In Monday's Pre-Market Sessio...,2016-12-05 08:29:19-05:00
1,Bank of America Upgrades ASML Holding N.V. to ...,2016-12-19 06:32:08-05:00
2,"Benzinga's Top Upgrades, Downgrades For Januar...",2017-01-17 09:22:35-05:00
3,"Earnings Scheduled For January 18, 2017\n\n \r...",2017-01-18 04:33:08-05:00
4,ASML +4.3% Premarket @$120.91; CFO Says 2017 i...,2017-01-18 07:55:31-05:00

In [9]:
%%time
df_news['token_len'] = df_news['text'].apply(lambda text: len(tokenizer.tokenize(text)))
df_news.head()

CPU times: user 14.8 s, sys: 9.88 ms, total: 14.8 s
Wall time: 14.9 s

,text,datetime,token_len
0,18 Stocks Moving In Monday's Pre-Market Sessio...,2016-12-05 08:29:19-05:00,803
1,Bank of America Upgrades ASML Holding N.V. to ...,2016-12-19 06:32:08-05:00,13
2,"Benzinga's Top Upgrades, Downgrades For Januar...",2017-01-17 09:22:35-05:00,1064
3,"Earnings Scheduled For January 18, 2017\n\n \r...",2017-01-18 04:33:08-05:00,737
4,ASML +4.3% Premarket @$120.91; CFO Says 2017 i...,2017-01-18 07:55:31-05:00,24

In [17]:
print(f"Percentage of texts with token length greater than 450: {df_news['token_len'].gt(450).sum()/len(df_news):.2%}")
df_news['token_len'].describe()

Percentage of texts with token length greater than 450: 53.82%

count      680.000000
mean      1491.572059
std       3261.417956
min          7.000000
25%        119.500000
50%        475.500000
75%        993.000000
max      29717.000000
Name: token_len, dtype: float64

In [18]:
display(df_news.loc[df_news['token_len'].idxmin()]['text'])

'UBS Upgrades ASML Holding to Buy\n\n'

In [19]:
display(df_news.loc[df_news['token_len'].idxmax()]['text'])

"Stocks That Hit 52-Week Lows On Monday. \xa0 \n During Monday's trading, 1214 companies set new 52-week lows. \n Facts of Interest About Today's 52-Week Lows: \n \n The largest company by market cap to set a new 52-week low was  Microsoft (NASDAQ: MSFT ) . \n Quoin Pharmaceuticals (NASDAQ: QNRX )  was the smallest company by market cap to set a new 52-week low. \n DexCom (NASDAQ: DXCM ) 's stock fell the most, as it traded down 76.5% to reach a new 52-week low. \n La Jolla Pharmaceutical (NASDAQ: LJPC ) 's stock made the biggest bounce back, actually moving up 0.0% shortly after hitting a new 52-week low. \n \n On Monday, the following stocks broke to new 52-week lows: \n \n Bank of America (NYSE: BAC )  stock hit a yearly low of $31.99. The stock was down 3.01% for the day. \n ASML Holding (NASDAQ: ASML )  shares moved down 4.86% on Monday to hit a new 52-week low of $491.62, drifting down 4.86%. \n Walt Disney (NYSE: DIS )  stock broke to a new 52-week low of $94.83 on Monday. Shares of the company traded down 3.68%. \n Oracle (NYSE: ORCL )  stock dropped to a yearly low on Monday of $64.29. Shares traded down 3.87%. \n Intel (NASDAQ: INTC )  stock achieved a new 52-week low on Monday morning, hitting $38.02 and moving down 2.71%. \n Texas Instruments (NASDAQ: TXN )  shares were down 2.17% for the day, having made a 52-week low of $154.02. \n Morgan Stanley (NYSE: MS )  stock hit a new 52-week low of $74.14. The stock was down 3.31% on the session. \n Medtronic (NYSE: MDT )  shares hit a yearly low of $90.37. The stock was down 1.98% on the session. \n Charles Schwab (NYSE: SCHW )  stock hit a new 52-week low of $59.35. The stock was down 3.65% on the session. \n American Express (NYSE: AXP )  stock drifted down 4.21% on Monday morning to hit a new 52-week low of $146.79. \n SAP (NYSE: SAP )  shares moved down 3.53% on Monday to hit a new 52-week low of $90.13, drifting down 3.53%. \n Applied Materials (NASDAQ: AMAT )  stock set a new 52-week low of $95.65 on Monday, moving down 5.63%. \n Stryker (NYSE: SYK )  stock hit $207.47 on Monday morning, setting a new 52-week low for a change of down 3.78%. \n 3M (NYSE: MMM )  stock hit $135.69 on Monday morning, setting a new 52-week low for a change of down 1.21%. \n Infosys (NYSE: INFY )  shares hit a yearly low of $17.76. The stock was down 2.45% on the session. \n General Electric (NYSE: GE )  stock broke to a new 52-week low of $67.32 on Monday. Shares of the company traded down 5.02%. \n Zoetis (NYSE: ZTS )  stock drifted down 3.91% on Monday morning to hit a new 52-week low of $154.33. \n U.S. Bancorp (NYSE: USB )  stock set a new 52-week low of $47.26 on Monday, moving down 2.47%. \n Boeing (NYSE: BA )  stock hit a new 52-week low of $115.33. The stock was down 8.81% on the session. \n Micron Technology (NASDAQ: MU )  stock hit $58.58 on Monday morning, setting a new 52-week low for a change of down 6.04%. \n CSX (NASDAQ: CSX )  shares hit a yearly low of $29.35. The stock was down 2.77% on the session. \n Airbnb (NASDAQ: ABNB )  stock hit a new 52-week low of $98.64. The stock was down 9.15% on the session. \n Truist Financial (NYSE: TFC )  stock hit a yearly low of $44.75. The stock was up 0.07% for the day. \n Illinois Tool Works (NYSE: ITW )  stock hit a new 52-week low of $189.89. The stock was down 3.15% on the session. \n Equinix (NASDAQ: EQIX )  shares made a new 52-week low of $617.16 on Monday. The stock was down 4.49% for the day. \n Ford Motor (NYSE: F )  stock dropped to a yearly low on Monday of $11.76. Shares traded down 6.94%. \n Canadian Imperial Bank (NYSE: CM )  shares hit a yearly low of $51.13. The stock was down 2.81% on the session. \n Ecolab (NYSE: ECL )  shares made a new 52-week low of $152.20 on Monday. The stock was down 3.71% for the day. \n Capital One Financial (NYSE: COF )  stock hit $107.01 on Monday morning, setting a new 52-week low for a change of down 4.06%. \n Roper Technologies (NYSE: ROP )  shares made a new 52-week low of $381.66 on Monday. The stock was down 0.32% for the day. \n Honda Motor Co (NYSE: HMC )  shares set a new 52-week low of $23.93. The stock traded down 2.81%. \n Takeda Pharmaceutical (NYSE: TAK )  shares hit a yearly low of $13.15. The stock was down 1.62% on the session. \n Stellantis (NYSE: STLA )  stock hit a yearly low of $12.89. The stock was down 4.44% for the day. \n Workday (NASDAQ: WDAY )  stock hit a new 52-week low of $141.35. The stock was down 5.05% on the session. \n Prudential Financial (NYSE: PRU )  stock hit a yearly low of $94.04. The stock was down 3.68% for the day. \n Chipotle Mexican Grill (NYSE: CMG )  shares were down 6.81% for the day, having made a 52-week low of $1,213.92. \n Bank of New York Mellon (NYSE: BK )  shares set a new 52-week low of $41.30. The stock traded down 3.03%. \n Parker Hannifin (NYSE: PH )  shares fell to $251.29 on Monday, setting a new 52-week low with a shift of down 4.01%. \n Ferrari (NYSE: RACE )  stock hit $171.66 on Monday morning, setting a new 52-week low for a change of down 4.55%. \n Global Payments (NYSE: GPN )  stock dropped to a yearly low on Monday of $110.88. Shares traded down 5.38%. \n DuPont de Nemours (NYSE: DD )  stock set a new 52-week low of $60.45 on Monday, moving down 4.45%. \n STMicroelectronics (NYSE: STM )  stock broke to a new 52-week low of $33.91 on Monday. Shares of the company traded down 6.09%. \n Carrier Global (NYSE: CARR )  shares were down 3.04% for the day, having made a 52-week low of $36.05. \n Illumina (NASDAQ: ILMN )  stock set a new 52-week low of $193.76 on Monday, moving down 4.42%. \n Wipro (NYSE: WIT )  shares fell to $5.55 on Monday, setting a new 52-week low with a shift of down 2.11%. \n Otis Worldwide (NYSE: OTIS )  shares made a new 52-week low of $70.45 on Monday. The stock was down 3.33% for the day. \n Apollo Global Management (NYSE: APO )  shares reached a new 52-week low of $48.92 on Monday morning, moving down 9.85%. \n BBVA (NYSE: BBVA )  stock hit a yearly low of $4.30. The stock was down 4.42% for the day. \n KKR & Co (NYSE: KKR )  shares moved down 7.86% on Monday to hit a new 52-week low of $46.56, drifting down 7.86%. \n CRH (NYSE: CRH )  shares made a new 52-week low of $35.35 on Monday. The stock was down 3.81% for the day. \n Corning (NYSE: GLW )  stock hit $31.57 on Monday morning, setting a new 52-week low for a change of down 4.59%. \n Discover Financial (NYSE: DFS )  stock set a new 52-week low of $93.11 on Monday, moving down 4.19%. \n Equity Residential (NYSE: EQR )  shares were down 3.69% for the day, having made a 52-week low of $69.40. \n AvalonBay Communities (NYSE: AVB )  shares moved down 3.93% on Monday to hit a new 52-week low of $186.75, drifting down 3.93%. \n AMETEK (NYSE: AME )  shares made a new 52-week low of $111.86 on Monday. The stock was down 2.86% for the day. \n Verisk Analytics (NASDAQ: VRSK )  stock set a new 52-week low of $159.08 on Monday, moving down 2.35%. \n Copart (NASDAQ: CPRT )  shares set a new 52-week low of $104.52. The stock traded down 3.12%. \n eBay (NASDAQ: EBAY )  stock hit a yearly low of $42.67. The stock was down 2.87% for the day. \n SVB Finl Gr (NASDAQ: SIVB )  stock achieved a new 52-week low on Monday morning, hitting $400.48 and moving down 7.85%. \n Fifth Third Bancorp (NASDAQ: FITB )  stock dropped to a yearly low on Monday of $34.19. Shares traded down 3.39%. \n Ferguson (NYSE: FERG )  stock broke to a new 52-week low of $108.38 on Monday. Shares of the company traded down 3.21%. \n CNH Industrial (NYSE: CNHI )  stock hit a new 52-week low of $12.85. The stock was down 4.7% on the session. \n Ball (NYSE: BALL )  stock hit a yearly low of $65.76. The stock was down 3.18% for the day. \n Invitation Homes (NYSE: INVH )  stock hit $34.02 on Monday morning, setting a new 52-week low for a change of down 5.43%. \n Northern Trust (NASDAQ: NTRS )  stock hit a yearly low of $97.94. The stock was down 2.66% for the day. \n Ansys (NASDAQ: ANSS )  shares reached a new 52-week low of $229.33 on Monday morning, moving down 4.86%. \n Martin Marietta Materials (NYSE: MLM )  stock set a new 52-week low of $312.08 on Monday, moving down 2.0%. \n Align Tech (NASDAQ: ALGN )  stock hit $242.67 on Monday morning, setting a new 52-week low for a change of down 5.29%. \n United Rentals (NYSE: URI )  stock set a new 52-week low of $261.80 on Monday, moving down 4.84%. \n Horizon Therapeutics (NASDAQ: HZNP )  shares set a new 52-week low of $81.66. The stock traded down 4.12%. \n Mid-America Apartment (NYSE: MAA )  shares made a new 52-week low of $161.75 on Monday. The stock was down 3.62% for the day. \n Garmin (NYSE: GRMN )  shares moved down 3.43% on Monday to hit a new 52-week low of $96.26, drifting down 3.43%. \n CGI (NYSE: GIB )  shares fell to $75.89 on Monday, setting a new 52-week low with a shift of down 3.68%. \n Dover (NYSE: DOV )  stock dropped to a yearly low on Monday of $123.88. Shares traded down 2.89%. \n Fox (NASDAQ: FOXA )  stock hit a new 52-week low of $31.32. The stock was down 2.79% on the session. \n Citizens Financial Group (NYSE: CFG )  stock hit a new 52-week low of $35.11. The stock was down 3.31% on the session. \n Paramount Global (NASDAQ: PARA )  shares moved down 6.59% on Monday to hit a new 52-week low of $26.05, drifting down 6.59%. \n Expedia Group (NASDAQ: EXPE )  stock hit $105.66 on Monday morning, setting a new 52-week low for a change of down 7.36%. \n KeyCorp (NYSE: KEY )  stock hit $17.12 on Monday morning, setting a new 52-week low for a change of down 2.59%. \n Best Buy Co (NYSE: BBY )  shares hit a yearly low of $68.80. The stock was down 4.17% on the session. \n Synchrony Finl (NYSE: SYF )  shares hit a yearly low of $29.89. The stock was down 3.52% on the session. \n Credit Suisse Group (NYSE: CS )  stock set a new 52-week low of $5.92 on Monday, moving down 3.65%. \n TransUnion (NYSE: TRU )  shares set a new yearly low of $77.84 this morning. The stock was down 0.88% on the session. \n Skyworks Solutions (NASDAQ: SWKS )  shares hit a yearly low of $93.31. The stock was down 6.32% on the session. \n Trimble (NASDAQ: TRMB )  shares set a new yearly low of $59.53 this morning. The stock was down 4.09% on the session. \n Akamai Technologies (NASDAQ: AKAM )  stock broke to a new 52-week low of $92.44 on Monday. Shares of the company traded down 4.81%. \n SS&C Technologies Hldgs (NASDAQ: SSNC )  stock dropped to a yearly low on Monday of $57.80. Shares traded down 4.07%. \n Pool (NASDAQ: POOL )  shares set a new yearly low of $366.68 this morning. The stock was down 4.38% on the session. \n KB Financial Group (NYSE: KB )  shares hit a yearly low of $41.01. The stock was down 3.79% on the session. \n Cloudflare (NYSE: NET )  stock achieved a new 52-week low on Monday morning, hitting $42.67 and moving down 9.54%. \n Xylem (NYSE: XYL )  stock achieved a new 52-week low on Monday morning, hitting $76.80 and moving down 3.79%. \n Camden Prop Trust (NYSE: CPT )  stock drifted down 3.99% on Monday morning to hit a new 52-week low of $127.78. \n UDR (NYSE: UDR )  stock hit $42.72 on Monday morning, setting a new 52-week low for a change of down 4.48%. \n Biomarin Pharmaceutical (NASDAQ: BMRN )  shares fell to $71.52 on Monday, setting a new 52-week low with a shift of down 4.34%. \n Entegris (NASDAQ: ENTG )  shares fell to $96.23 on Monday, setting a new 52-week low with a shift of down 6.74%. \n Healthpeak Properties (NYSE: PEAK )  stock set a new 52-week low of $24.20 on Monday, moving down 5.4%. \n NortonLifeLock (NASDAQ: NLOK )  stock hit a new 52-week low of $22.41. The stock was down 2.2% on the session. \n ZoomInfo Technologies (NASDAQ: ZI )  stock hit $31.61 on Monday morning, setting a new 52-week low for a change of down 9.15%. \n Eastman Chemical (NYSE: EMN )  stock dropped to a yearly low on Monday of $97.56. Shares traded down 4.25%. \n Smith & Nephew (NYSE: SNN )  shares were down 4.16% for the day, having made a 52-week low of $28.37. \n MGM Resorts Intl (NYSE: MGM )  shares made a new 52-week low of $28.57 on Monday. The stock was down 8.87% for the day. \n Liberty SiriusXM Gr (NASDAQ: LSXMA )  stock dropped to a yearly low on Monday of $37.05. Shares traded down 3.39%. \n Kimco Realty (NYSE: KIM )  stock set a new 52-week low of $19.41 on Monday, moving down 5.59%. \n Carlyle Group (NASDAQ: CG )  shares fell to $33.11 on Monday, setting a new 52-week low with a shift of down 7.45%. \n American Homes 4 Rent (NYSE: AMH )  shares made a new 52-week low of $34.00 on Monday. The stock was down 5.27% for the day. \n DocuSign (NASDAQ: DOCU )  shares made a new 52-week low of $58.00 on Monday. The stock was down 11.1% for the day. \n Carnival (NYSE: CCL )  shares made a new 52-week low of $9.79 on Monday. The stock was down 10.0% for the day. \n Franklin Resources (NYSE: BEN )  stock drifted down 5.27% on Monday morning to hit a new 52-week low of $23.17. \n Nordson (NASDAQ: NDSN )  shares hit a yearly low of $200.36. The stock was down 3.12% on the session. \n Crown Holdings (NYSE: CCK )  shares reached a new 52-week low of $92.69 on Monday morning, moving down 6.24%. \n Ally Financial (NYSE: ALLY )  shares reached a new 52-week low of $35.08 on Monday morning, moving down 5.99%. \n Liberty Global (NASDAQ: LBTYB )  shares set a new 52-week low of $22.45. The stock traded down 3.61%. \n Signature Bank (NASDAQ: SBNY )  stock hit a new 52-week low of $170.76. The stock was down 14.08% on the session. \n Enel Americas (NYSE: ENIA )  shares set a new 52-week low of $5.00. The stock traded down 2.72%. \n Royal Caribbean Gr (NYSE: RCL )  shares fell to $41.10 on Monday, setting a new 52-week low with a shift of down 8.13%. \n Charles River (NYSE: CRL )  shares set a new yearly low of $208.73 this morning. The stock was down 4.33% on the session. \n Fidelity National Finl (NYSE: FNF )  stock drifted down 3.79% on Monday morning to hit a new 52-week low of $37.21. \n Advance Auto Parts (NYSE: AAP )  shares set a new yearly low of $171.33 this morning. The stock was down 4.34% on the session. \n James Hardie Industries (NYSE: JHX )  stock achieved a new 52-week low on Monday morning, hitting $22.54 and moving down 3.44%. \n InterContinental Hotels (NYSE: IHG )  stock drifted down 7.72% on Monday morning to hit a new 52-week low of $53.20. \n SK Telecom Co (NYSE: SKM )  stock hit a yearly low of $23.32. The stock was down 1.64% for the day. \n Medical Properties Trust (NYSE: MPW )  shares made a new 52-week low of $15.05 on Monday. The stock was down 5.0% for the day. \n Annaly Capital Management (NYSE: NLY )  stock hit a yearly low of $6.17. The stock was down 4.91% for the day. \n East West Bancorp (NASDAQ: EWBC )  shares moved down 3.37% on Monday to hit a new 52-week low of $63.36, drifting down 3.37%. \n CubeSmart (NYSE: CUBE )  stock drifted down 4.69% on Monday morning to hit a new 52-week low of $39.38. \n DaVita (NYSE: DVA )  stock dropped to a yearly low on Monday of $91.15. Shares traded down 1.55%. \n Logitech International (NASDAQ: LOGI )  shares hit a yearly low of $52.27. The stock was down 4.91% on the session. \n Caesars Entertainment (NASDAQ: CZR )  shares reached a new 52-week low of $39.58 on Monday morning, moving down 11.93%. \n Lincoln National (NYSE: LNC )  shares made a new 52-week low of $47.97 on Monday. The stock was down 5.4% for the day. \n Universal Health Services (NYSE: UHS )  stock achieved a new 52-week low on Monday morning, hitting $109.09 and moving down 3.83%. \n Zillow Gr (NASDAQ: ZG )  shares set a new yearly low of $32.50 this morning. The stock was down 8.26% on the session. \n Webster Finl (NYSE: WBS )  stock set a new 52-week low of $44.07 on Monday, moving down 3.61%. \n Western Alliance (NYSE: WAL )  stock hit a new 52-week low of $71.43. The stock was down 2.52% on the session. \n Advanced Drainage Systems (NYSE: WMS )  shares fell to $89.28 on Monday, setting a new 52-week low with a shift of down 5.61%. \n Bath & Body Works (NYSE: BBWI )  stock achieved a new 52-week low on Monday morning, hitting $32.09 and moving down 4.57%. \n Invesco (NYSE: IVZ )  shares hit a yearly low of $15.85. The stock was down 7.81% on the session. \n National Retail Props (NYSE: NNN )  shares were down 4.51% for the day, having made a 52-week low of $40.32. \n Lennox International (NYSE: LII )  stock dropped to a yearly low on Monday of $195.42. Shares traded down 2.28%. \n STORE Capital (NYSE: STOR )  stock drifted down 5.12% on Monday morning to hit a new 52-week low of $24.98. \n Exact Sciences (NASDAQ: EXAS )  shares were down 8.66% for the day, having made a 52-week low of $37.08. \n Starwood Property Trust (NYSE: STWD )  shares fell to $21.19 on Monday, setting a new 52-week low with a shift of down 3.48%. \n Syneos Health (NASDAQ: SYNH )  shares hit a yearly low of $63.78. The stock was down 5.36% on the session. \n Gol Intelligent Airlines (NYSE: GOL )  stock set a new 52-week low of $3.95 on Monday, moving down 12.96%. \n Tenet Healthcare (NYSE: THC )  shares made a new 52-week low of $58.64 on Monday. The stock was down 5.71% for the day. \n US Foods Hldg (NYSE: USFD )  stock hit $28.22 on Monday morning, setting a new 52-week low for a change of down 3.22%. \n First Industrial Realty (NYSE: FR )  shares made a new 52-week low of $47.45 on Monday. The stock was down 3.99% for the day. \n Robinhood Markets (NASDAQ: HOOD )  stock set a new 52-week low of $7.02 on Monday, moving down 8.96%. \n Stifel Financial (NYSE: SF )  stock hit a new 52-week low of $56.74. The stock was down 4.47% on the session. \n Dun & Bradstreet Hldgs (NYSE: DNB )  shares made a new 52-week low of $13.96 on Monday. The stock was down 4.58% for the day. \n Brixmor Property Group (NYSE: BRX )  shares set a new yearly low of $20.25 this morning. The stock was down 6.72% on the session. \n Globus Medical (NYSE: GMED )  shares hit a yearly low of $56.64. The stock was down 3.64% on the session. \n Vornado Realty (NYSE: VNO )  stock broke to a new 52-week low of $29.19 on Monday. Shares of the company traded down 5.98%. \n Woodward (NASDAQ: WWD )  shares fell to $92.19 on Monday, setting a new 52-week low with a shift of down 3.75%. \n Stag Industrial (NYSE: STAG )  shares were down 3.76% for the day, having made a 52-week low of $30.72. \n Valley National (NASDAQ: VLY )  shares set a new 52-week low of $10.80. The stock traded down 2.15%. \n Pinnacle Finl Partners (NASDAQ: PNFP )  stock dropped to a yearly low on Monday of $71.41. Shares traded down 2.1%. \n First Finl Bankshares (NASDAQ: FFIN )  stock hit $37.88 on Monday morning, setting a new 52-week low for a change of down 0.36%. \n SiteOne Landscape Supply (NYSE: SITE )  shares set a new 52-week low of $117.19. The stock traded down 4.21%. \n Synovus Finl (NYSE: SNV )  stock set a new 52-week low of $35.77 on Monday, moving down 4.49%. \n Universal Display (NASDAQ: OLED )  shares were down 6.07% for the day, having made a 52-week low of $109.72. \n Gildan Activewear (NYSE: GIL )  shares reached a new 52-week low of $27.67 on Monday morning, moving down 4.72%. \n Alaska Air Gr (NYSE: ALK )  stock drifted down 6.43% on Monday morning to hit a new 52-week low of $41.12. \n Spirit Realty Cap (NYSE: SRC )  shares moved down 5.6% on Monday to hit a new 52-week low of $37.24, drifting down 5.6%. \n Lyft (NASDAQ: LYFT )  shares moved down 9.19% on Monday to hit a new 52-week low of $14.26, drifting down 9.19%. \n Synaptics (NASDAQ: SYNA )  shares made a new 52-week low of $124.09 on Monday. The stock was down 6.59% for the day. \n New York Times (NYSE: NYT )  shares set a new yearly low of $29.13 this morning. The stock was down 9.65% on the session. \n Scotts Miracle Gro (NYSE: SMG )  shares hit a yearly low of $86.78. The stock was down 1.52% on the session. \n Norwegian Cruise Line (NYSE: NCLH )  shares fell to $11.50 on Monday, setting a new 52-week low with a shift of down 11.25%. \n Blackstone Mortgage Trust (NYSE: BXMT )  shares set a new 52-week low of $28.28.

In [61]:
print(df_news['text'][4])
pipe(df_news['text'][4])

ASML +4.3% Premarket @$120.91; CFO Says 2017 is Going to be a Great Year

[{'label': 'Positive', 'score': 1.0}]

In [55]:
def convert_to_score(sentiment):
    if 'negative' in sentiment.lower():
        return -1
    elif 'positive' in sentiment.lower():
        return 1
    else:
        return 0

def sliding_window_chunks(text, window_size, stride):
    tokens = tokenizer(text)["input_ids"]
    token_chunks = [tokens[i:i + window_size] for i in range(0, len(tokens), stride) if i + window_size <= len(tokens)]
    return token_chunks

# parameters for chunking
window_size = 450
stride = 225  # overlap length

In [57]:
sentiment_scores = []
for index, row in tqdm(df_news.iterrows(), total=len(df_news), desc="Processing news texts..."):
    text = row['text']
    if len(tokenizer(text)["input_ids"]) > window_size:
        scores = []
        for chunk in sliding_window_chunks(text, window_size, stride):
            scores.append(convert_to_score(pipe(tokenizer.decode(chunk))[0]['label']))
        sentiment_score = max(set(scores), key=scores.count)
        sentiment_scores.append(sentiment_score)
    else:
        sentiment_scores.append(convert_to_score(pipe(text)[0]['label']))

Processing news texts...: 100%|██████████| 680/680 [1:34:33<00:00,  8.34s/it]

In [58]:
with open('sentiment_scores.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows([sentiment_scores])

## FinGPT v3
Another LLM worth trying, but not very scalable and takes too much GPU RAM for inferencing

In [ ]:
base_model = "NousResearch/Llama-2-13b-hf"
peft_model = "FinGPT/fingpt-sentiment_llama2-13b_lora"
tokenizer = LlamaTokenizerFast.from_pretrained(base_model)
tokenizer.pad_token = tokenizer.eos_token
model = LlamaForCausalLM.from_pretrained(base_model, device_map='cuda:0', load_in_8bit=True) # GPU is used
model = PeftModel.from_pretrained(model, peft_model)
model = model.eval()

tokenizer_config.json:   0%|          | 0.00/746 [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/435 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/631 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/33.4k [00:00<?, ?B/s]

Downloading shards:   0%|          | 0/3 [00:00<?, ?it/s]

model-00001-of-00003.safetensors:   0%|          | 0.00/9.95G [00:00<?, ?B/s]

model-00002-of-00003.safetensors:   0%|          | 0.00/9.90G [00:00<?, ?B/s]

model-00003-of-00003.safetensors:   0%|          | 0.00/6.18G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/175 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:381: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:386: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(

adapter_config.json:   0%|          | 0.00/462 [00:00<?, ?B/s]

adapter_model.bin:   0%|          | 0.00/19.7M [00:00<?, ?B/s]

In [ ]:
# prompt = [
# '''Instruction: What is the sentiment of this news? Choose an answer from {negative/neutral/positive}
# Input: FINANCING OF ASPOCOMP 'S GROWTH Aspocomp is aggressively pursuing its growth strategy by increasingly focusing on technologically more demanding HDI printed circuit boards PCBs .
# Answer: ''',
# '''Instruction: What is the sentiment of this news? Choose an answer from {negative/neutral/positive}
# Input: According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing .
# Answer: ''',
# '''Instruction: What is the sentiment of this news? Choose an answer from {negative/neutral/positive}
# Input: A tinyurl link takes users to a scamming site promising that users can earn thousands of dollars by becoming a Google ( NASDAQ : GOOG ) Cash advertiser .
# Answer: ''',
# ]

# with torch.inference_mode():
#     tokens = tokenizer(prompt, return_tensors='pt', padding=True, max_length=512)
#     res = model.generate(**tokens, max_length=512)
#     res_sentences = [tokenizer.decode(i) for i in res]
#     out_text = [o.split("Answer: ")[1] for o in res_sentences]

# for sentiment in out_text:
#     print(sentiment)

# del res, tokens, res_sentences, out_text
# gc.collect()
# torch.cuda.empty_cache()

In [ ]:
symbol = 'ASML'
sentiment_scores = []

with torch.inference_mode():
    for index, row in tqdm(df_news.iterrows(), total=len(df_news), desc="Processing news texts..."):
        text = row['text']
        # if text is about to exceed maximum input length
        if len(tokenizer(text)["input_ids"]) > window_size:
            # the following commented section is for inferencing in batches if GPU has **enough** memory

            # prompts = [f'''Instruction: What is the sentiment of {symbol} in this news?
            # Choose an answer from {{negative/neutral/positive}}
            # Input: {tokenizer.decode(chunk)}
            # Answer: ''' for chunk in sliding_window_chunks(text, window_size, stride)]
            # tokens = tokenizer(prompts, return_tensors='pt', padding=True, max_length=512, truncation=True)
            # # tokens = {k: v.to("cuda:0") for k, v in tokens.items()} # move tokens to the same device as the model
            # res = model.generate(**tokens, max_length=512)
            # res_sentences = [tokenizer.decode(i) for i in res]
            # sentiments = [o.split("Answer: ")[1] for o in res_sentences]
            # scores = [convert_to_score(sentiment) for sentiment in sentiments]
            # # free memory
            # del tokens, res, res_sentences
            # gc.collect()
            # torch.cuda.empty_cache()
            # # aggregate scores by majority voting
            # sentiment_scores.append(max(set(scores), key=scores.count))

            scores = []
            for chunk in sliding_window_chunks(text, window_size, stride):
                prompt = f'''Instruction: What is the sentiment of {symbol} in this news?
                            Choose an answer from {{negative/neutral/positive}}
                            Input: {tokenizer.decode(chunk)}
                            Answer: '''
                tokens = tokenizer(prompt, return_tensors='pt', padding=True, max_length=512, truncation=True)
                # tokens = {k: v.to("cuda:0") for k, v in tokens.items()}
                res = model.generate(**tokens, max_length=512)
                res_sentence = [tokenizer.decode(i) for i in res]
                sentiment = [o.split("Answer: ")[1] for o in res_sentence][0]
                scores.append(convert_to_score(sentiment))
                # free memory
                del tokens, res, res_sentence
                gc.collect()
                torch.cuda.empty_cache()
            # aggregate scores by majority voting
            sentiment_scores.append(max(set(scores), key=scores.count))
            print([index, max(set(scores), key=scores.count)])
        else:
            prompt = [
            f'''Instruction: What is the sentiment of {symbol} in this news?
            Choose an answer from {{negative/neutral/positive}}
            Input: {text}
            Answer: '''
            ]
            tokens = tokenizer(prompt, return_tensors='pt', padding=True, max_length=512, truncation=True)
            # tokens = {k: v.to("cuda:0") for k, v in tokens.items()} # move tokens to the same device as the model
            response = model.generate(**tokens, max_length=512)
            response_sentences = [tokenizer.decode(i) for i in response]
            sentiment = [o.split("Answer: ")[1] for o in response_sentences][0]
            sentiment_scores.append(convert_to_score(sentiment))
            print([index, convert_to_score(sentiment)])
            # free memory
            del tokens, response, response_sentences
            gc.collect()
            torch.cuda.empty_cache()